/**
 * All 24 galleries from her live site, with real couple names and titles.
 *
 * Generated by scripts/harvest-curated.mjs — do not hand-edit.
 * The live site holds 3,723 photographs in total; 288 are bundled here,
 * up to 12 per gallery. Titles and names are hers, verbatim.
 */
export type Gallery = {
  slug: string;
  title: string;
  kind: 'Wedding' | 'Engagement' | 'Bachelorette';
  cover: string;
  photos: string[];
};

export const galleries: Gallery[] = [
  {
    "slug": "lucka-domen",
    "title": "Lučka & Domen",
    "kind": "Wedding",
    "cover": "lucka-domen--lucka-in-domen-organizator-porok-ljubljana-1",
    "photos": [
      "lucka-domen--lucka-in-domen-organizator-porok-ljubljana-1",
      "lucka-domen--lucka-in-domen-organizator-porok-ljubljana-10",
      "lucka-domen--lucka-in-domen-organizator-porok-ljubljana-100",
      "lucka-domen--lucka-in-domen-organizator-porok-ljubljana-101",
      "lucka-domen--lucka-in-domen-organizator-porok-ljubljana-102",
      "lucka-domen--lucka-in-domen-organizator-porok-ljubljana-103",
      "lucka-domen--lucka-in-domen-organizator-porok-ljubljana-104",
      "lucka-domen--lucka-in-domen-organizator-porok-ljubljana-105",
      "lucka-domen--lucka-in-domen-organizator-porok-ljubljana-106",
      "lucka-domen--lucka-in-domen-organizator-porok-ljubljana-107",
      "lucka-domen--lucka-in-domen-organizator-porok-ljubljana-108",
      "lucka-domen--lucka-in-domen-organizator-porok-ljubljana-109"
    ]
  },
  {
    "slug": "zimska-zaroka",
    "title": "Zimska zaroka",
    "kind": "Engagement",
    "cover": "zimska-zaroka--zimska-zaroka-organizacija-zarok-1",
    "photos": [
      "zimska-zaroka--zimska-zaroka-organizacija-zarok-1",
      "zimska-zaroka--zimska-zaroka-organizacija-zarok-10",
      "zimska-zaroka--zimska-zaroka-organizacija-zarok-11",
      "zimska-zaroka--zimska-zaroka-organizacija-zarok-12",
      "zimska-zaroka--zimska-zaroka-organizacija-zarok-13",
      "zimska-zaroka--zimska-zaroka-organizacija-zarok-14",
      "zimska-zaroka--zimska-zaroka-organizacija-zarok-15",
      "zimska-zaroka--zimska-zaroka-organizacija-zarok-16",
      "zimska-zaroka--zimska-zaroka-organizacija-zarok-17",
      "zimska-zaroka--zimska-zaroka-organizacija-zarok-18",
      "zimska-zaroka--zimska-zaroka-organizacija-zarok-19",
      "zimska-zaroka--zimska-zaroka-organizacija-zarok-2"
    ]
  },
  {
    "slug": "urska-primoz",
    "title": "Urška & Primož",
    "kind": "Wedding",
    "cover": "urska-primoz--urska-in-primoz-organizator-porok-piran-1",
    "photos": [
      "urska-primoz--urska-in-primoz-organizator-porok-piran-1",
      "urska-primoz--urska-in-primoz-organizator-porok-piran-10",
      "urska-primoz--urska-in-primoz-organizator-porok-piran-100",
      "urska-primoz--urska-in-primoz-organizator-porok-piran-101",
      "urska-primoz--urska-in-primoz-organizator-porok-piran-102",
      "urska-primoz--urska-in-primoz-organizator-porok-piran-103",
      "urska-primoz--urska-in-primoz-organizator-porok-piran-104",
      "urska-primoz--urska-in-primoz-organizator-porok-piran-105",
      "urska-primoz--urska-in-primoz-organizator-porok-piran-106",
      "urska-primoz--urska-in-primoz-organizator-porok-piran-107",
      "urska-primoz--urska-in-primoz-organizator-porok-piran-108",
      "urska-primoz--urska-in-primoz-organizator-porok-piran-109"
    ]
  },
  {
    "slug": "ursa-matija",
    "title": "Urša & Matija",
    "kind": "Wedding",
    "cover": "ursa-matija--ursa-in-matija-organizator-poroke-1",
    "photos": [
      "ursa-matija--ursa-in-matija-organizator-poroke-1",
      "ursa-matija--ursa-in-matija-organizator-poroke-10",
      "ursa-matija--ursa-in-matija-organizator-poroke-11",
      "ursa-matija--ursa-in-matija-organizator-poroke-12",
      "ursa-matija--ursa-in-matija-organizator-poroke-13",
      "ursa-matija--ursa-in-matija-organizator-poroke-14",
      "ursa-matija--ursa-in-matija-organizator-poroke-15",
      "ursa-matija--ursa-in-matija-organizator-poroke-16",
      "ursa-matija--ursa-in-matija-organizator-poroke-17",
      "ursa-matija--ursa-in-matija-organizator-poroke-18",
      "ursa-matija--ursa-in-matija-organizator-poroke-19",
      "ursa-matija--ursa-in-matija-organizator-poroke-2"
    ]
  },
  {
    "slug": "ulla-matjaz",
    "title": "Ulla & Matjaž",
    "kind": "Wedding",
    "cover": "ulla-matjaz--ulla-in-matjaz-organizator-porok-ljubljana-1",
    "photos": [
      "ulla-matjaz--ulla-in-matjaz-organizator-porok-ljubljana-1",
      "ulla-matjaz--ulla-in-matjaz-organizator-porok-ljubljana-10",
      "ulla-matjaz--ulla-in-matjaz-organizator-porok-ljubljana-100",
      "ulla-matjaz--ulla-in-matjaz-organizator-porok-ljubljana-101",
      "ulla-matjaz--ulla-in-matjaz-organizator-porok-ljubljana-102",
      "ulla-matjaz--ulla-in-matjaz-organizator-porok-ljubljana-103",
      "ulla-matjaz--ulla-in-matjaz-organizator-porok-ljubljana-104",
      "ulla-matjaz--ulla-in-matjaz-organizator-porok-ljubljana-105",
      "ulla-matjaz--ulla-in-matjaz-organizator-porok-ljubljana-106",
      "ulla-matjaz--ulla-in-matjaz-organizator-porok-ljubljana-107",
      "ulla-matjaz--ulla-in-matjaz-organizator-porok-ljubljana-108",
      "ulla-matjaz--ulla-in-matjaz-organizator-porok-ljubljana-109"
    ]
  },
  {
    "slug": "tina-dejan",
    "title": "Tina & Dejan",
    "kind": "Wedding",
    "cover": "tina-dejan--tina-in-dejan-organizator-porok-bled-1",
    "photos": [
      "tina-dejan--tina-in-dejan-organizator-porok-bled-1",
      "tina-dejan--tina-in-dejan-organizator-porok-bled-10",
      "tina-dejan--tina-in-dejan-organizator-porok-bled-100",
      "tina-dejan--tina-in-dejan-organizator-porok-bled-101",
      "tina-dejan--tina-in-dejan-organizator-porok-bled-102",
      "tina-dejan--tina-in-dejan-organizator-porok-bled-103",
      "tina-dejan--tina-in-dejan-organizator-porok-bled-104",
      "tina-dejan--tina-in-dejan-organizator-porok-bled-105",
      "tina-dejan--tina-in-dejan-organizator-porok-bled-106",
      "tina-dejan--tina-in-dejan-organizator-porok-bled-107",
      "tina-dejan--tina-in-dejan-organizator-porok-bled-108",
      "tina-dejan--tina-in-dejan-organizator-porok-bled-109"
    ]
  },
  {
    "slug": "sheila-matej",
    "title": "Sheila & Matej",
    "kind": "Wedding",
    "cover": "sheila-matej--s-m-samo-rovan-0006",
    "photos": [
      "sheila-matej--s-m-samo-rovan-0006",
      "sheila-matej--s-m-samo-rovan-0011",
      "sheila-matej--s-m-samo-rovan-0013",
      "sheila-matej--s-m-samo-rovan-0059",
      "sheila-matej--s-m-samo-rovan-0063",
      "sheila-matej--s-m-samo-rovan-0064",
      "sheila-matej--s-m-samo-rovan-0065",
      "sheila-matej--s-m-samo-rovan-0066",
      "sheila-matej--s-m-samo-rovan-0067",
      "sheila-matej--s-m-samo-rovan-0068",
      "sheila-matej--s-m-samo-rovan-0070",
      "sheila-matej--s-m-samo-rovan-0129"
    ]
  },
  {
    "slug": "jasmina-matic",
    "title": "Jasmina & Matic",
    "kind": "Wedding",
    "cover": "jasmina-matic--rimske-terme-vse-samo-rovan-075",
    "photos": [
      "jasmina-matic--rimske-terme-vse-samo-rovan-075",
      "jasmina-matic--rimske-terme-vse-samo-rovan-079",
      "jasmina-matic--rimske-terme-vse-samo-rovan-080",
      "jasmina-matic--rimske-terme-vse-samo-rovan-081",
      "jasmina-matic--rimske-terme-vse-samo-rovan-083",
      "jasmina-matic--rimske-terme-vse-samo-rovan-084",
      "jasmina-matic--rimske-terme-vse-samo-rovan-085",
      "jasmina-matic--rimske-terme-vse-samo-rovan-086",
      "jasmina-matic--rimske-terme-vse-samo-rovan-087",
      "jasmina-matic--rimske-terme-vse-samo-rovan-088",
      "jasmina-matic--rimske-terme-vse-samo-rovan-089",
      "jasmina-matic--rimske-terme-vse-samo-rovan-090"
    ]
  },
  {
    "slug": "zaroka-j-m",
    "title": "Zaroka J & M",
    "kind": "Engagement",
    "cover": "zaroka-j-m--rimske-terme-vse-samo-rovan-220",
    "photos": [
      "zaroka-j-m--rimske-terme-vse-samo-rovan-220",
      "zaroka-j-m--rimske-terme-vse-samo-rovan-221",
      "zaroka-j-m--rimske-terme-vse-samo-rovan-222",
      "zaroka-j-m--rimske-terme-vse-samo-rovan-223",
      "zaroka-j-m--rimske-terme-vse-samo-rovan-224",
      "zaroka-j-m--rimske-terme-vse-samo-rovan-225",
      "zaroka-j-m--rimske-terme-vse-samo-rovan-226",
      "zaroka-j-m--rimske-terme-vse-samo-rovan-227",
      "zaroka-j-m--rimske-terme-vse-samo-rovan-228",
      "zaroka-j-m--rimske-terme-vse-samo-rovan-229",
      "zaroka-j-m--rimske-terme-vse-samo-rovan-230",
      "zaroka-j-m--rimske-terme-vse-samo-rovan-231"
    ]
  },
  {
    "slug": "anina-dekliscina",
    "title": "Anina dekliščina",
    "kind": "Bachelorette",
    "cover": "anina-dekliscina--rimske-terme-vse-samo-rovan-001",
    "photos": [
      "anina-dekliscina--rimske-terme-vse-samo-rovan-001",
      "anina-dekliscina--rimske-terme-vse-samo-rovan-002",
      "anina-dekliscina--rimske-terme-vse-samo-rovan-003",
      "anina-dekliscina--rimske-terme-vse-samo-rovan-004",
      "anina-dekliscina--rimske-terme-vse-samo-rovan-005",
      "anina-dekliscina--rimske-terme-vse-samo-rovan-006",
      "anina-dekliscina--rimske-terme-vse-samo-rovan-007",
      "anina-dekliscina--rimske-terme-vse-samo-rovan-008",
      "anina-dekliscina--rimske-terme-vse-samo-rovan-009",
      "anina-dekliscina--rimske-terme-vse-samo-rovan-010",
      "anina-dekliscina--rimske-terme-vse-samo-rovan-011",
      "anina-dekliscina--rimske-terme-vse-samo-rovan-012"
    ]
  },
  {
    "slug": "sonja-miha",
    "title": "Sonja & Miha",
    "kind": "Wedding",
    "cover": "sonja-miha--navidezna-piran-ana-kete-photo-200-1",
    "photos": [
      "sonja-miha--navidezna-piran-ana-kete-photo-200-1",
      "sonja-miha--navidezna-piran-ana-kete-photo-201-1",
      "sonja-miha--navidezna-piran-ana-kete-photo-202-1",
      "sonja-miha--navidezna-piran-ana-kete-photo-205-1",
      "sonja-miha--navidezna-piran-ana-kete-photo-206-1",
      "sonja-miha--navidezna-piran-ana-kete-photo-208-1",
      "sonja-miha--navidezna-piran-ana-kete-photo-218-1",
      "sonja-miha--navidezna-piran-ana-kete-photo-219-1",
      "sonja-miha--navidezna-piran-ana-kete-photo-225-1",
      "sonja-miha--navidezna-piran-ana-kete-photo-226-1",
      "sonja-miha--navidezna-piran-ana-kete-photo-231-1",
      "sonja-miha--navidezna-piran-ana-kete-photo-243-1"
    ]
  },
  {
    "slug": "maja-luka",
    "title": "Maja & Luka",
    "kind": "Wedding",
    "cover": "maja-luka--image0-2",
    "photos": [
      "maja-luka--image0-2",
      "maja-luka--image1-2",
      "maja-luka--image2",
      "maja-luka--image3",
      "maja-luka--image4",
      "maja-luka--m-lweb-001",
      "maja-luka--m-lweb-003",
      "maja-luka--m-lweb-004",
      "maja-luka--m-lweb-005",
      "maja-luka--m-lweb-008",
      "maja-luka--m-lweb-012",
      "maja-luka--m-lweb-016"
    ]
  },
  {
    "slug": "luka-ana",
    "title": "Luka & Ana",
    "kind": "Wedding",
    "cover": "luka-ana--1-20210529-luka-in-ana-0001",
    "photos": [
      "luka-ana--1-20210529-luka-in-ana-0001",
      "luka-ana--1-luka-ana-poroka1",
      "luka-ana--10-20210529-luka-in-ana-0009",
      "luka-ana--10-luka-ana-poroka10",
      "luka-ana--100-luka-ana-poroka100",
      "luka-ana--11-20210529-luka-in-ana-0010",
      "luka-ana--11-luka-ana-poroka11",
      "luka-ana--12-20210529-luka-in-ana-0012",
      "luka-ana--12-luka-ana-poroka12",
      "luka-ana--13-luka-ana-poroka13",
      "luka-ana--135-luka-ana-poroka135",
      "luka-ana--136-luka-ana-poroka136"
    ]
  },
  {
    "slug": "lara-matija",
    "title": "Lara & Matija",
    "kind": "Wedding",
    "cover": "lara-matija--1-1",
    "photos": [
      "lara-matija--1-1",
      "lara-matija--100-1",
      "lara-matija--101-1",
      "lara-matija--102-1",
      "lara-matija--11-1",
      "lara-matija--118-1",
      "lara-matija--119-1",
      "lara-matija--12-1",
      "lara-matija--120-1",
      "lara-matija--121-1",
      "lara-matija--122-1",
      "lara-matija--123-1"
    ]
  },
  {
    "slug": "karin-tomaz",
    "title": "Karin & Tomaž",
    "kind": "Wedding",
    "cover": "karin-tomaz--www-aljazhafner-com-poroka-karin-tomaz-007",
    "photos": [
      "karin-tomaz--www-aljazhafner-com-poroka-karin-tomaz-007",
      "karin-tomaz--www-aljazhafner-com-poroka-karin-tomaz-011",
      "karin-tomaz--www-aljazhafner-com-poroka-karin-tomaz-012",
      "karin-tomaz--www-aljazhafner-com-poroka-karin-tomaz-013",
      "karin-tomaz--www-aljazhafner-com-poroka-karin-tomaz-014",
      "karin-tomaz--www-aljazhafner-com-poroka-karin-tomaz-016",
      "karin-tomaz--www-aljazhafner-com-poroka-karin-tomaz-017",
      "karin-tomaz--www-aljazhafner-com-poroka-karin-tomaz-018",
      "karin-tomaz--www-aljazhafner-com-poroka-karin-tomaz-020",
      "karin-tomaz--www-aljazhafner-com-poroka-karin-tomaz-021",
      "karin-tomaz--www-aljazhafner-com-poroka-karin-tomaz-022",
      "karin-tomaz--www-aljazhafner-com-poroka-karin-tomaz-023"
    ]
  },
  {
    "slug": "kaja-damjan",
    "title": "Kaja & Damjan",
    "kind": "Wedding",
    "cover": "kaja-damjan--124-1",
    "photos": [
      "kaja-damjan--124-1",
      "kaja-damjan--130-1",
      "kaja-damjan--143-1",
      "kaja-damjan--144-1",
      "kaja-damjan--145-1",
      "kaja-damjan--15-1",
      "kaja-damjan--19-1",
      "kaja-damjan--1ca52bdd-84b9-442b-86de-2fd0b6cd2bb1",
      "kaja-damjan--20-1",
      "kaja-damjan--21-1",
      "kaja-damjan--22-1",
      "kaja-damjan--22665af1-d92f-43e8-a9fa-c86a798b0d48"
    ]
  },
  {
    "slug": "ivona-matic",
    "title": "Ivona & Matic",
    "kind": "Wedding",
    "cover": "ivona-matic--ivonamatic-1",
    "photos": [
      "ivona-matic--ivonamatic-1",
      "ivona-matic--ivonamatic-101",
      "ivona-matic--ivonamatic-102",
      "ivona-matic--ivonamatic-108",
      "ivona-matic--ivonamatic-109",
      "ivona-matic--ivonamatic-110",
      "ivona-matic--ivonamatic-111",
      "ivona-matic--ivonamatic-1119",
      "ivona-matic--ivonamatic-1120",
      "ivona-matic--ivonamatic-1125",
      "ivona-matic--ivonamatic-1126",
      "ivona-matic--ivonamatic-1127"
    ]
  },
  {
    "slug": "doroteja-matic",
    "title": "Doroteja & Matic",
    "kind": "Wedding",
    "cover": "doroteja-matic--doroteja-in-matic-organizacija-porok-primorska-1",
    "photos": [
      "doroteja-matic--doroteja-in-matic-organizacija-porok-primorska-1",
      "doroteja-matic--doroteja-in-matic-organizacija-porok-primorska-10",
      "doroteja-matic--doroteja-in-matic-organizacija-porok-primorska-100",
      "doroteja-matic--doroteja-in-matic-organizacija-porok-primorska-101",
      "doroteja-matic--doroteja-in-matic-organizacija-porok-primorska-102",
      "doroteja-matic--doroteja-in-matic-organizacija-porok-primorska-103",
      "doroteja-matic--doroteja-in-matic-organizacija-porok-primorska-104",
      "doroteja-matic--doroteja-in-matic-organizacija-porok-primorska-105",
      "doroteja-matic--doroteja-in-matic-organizacija-porok-primorska-106",
      "doroteja-matic--doroteja-in-matic-organizacija-porok-primorska-107",
      "doroteja-matic--doroteja-in-matic-organizacija-porok-primorska-108",
      "doroteja-matic--doroteja-in-matic-organizacija-porok-primorska-109"
    ]
  },
  {
    "slug": "bozicna-zaroka",
    "title": "Božična zaroka",
    "kind": "Engagement",
    "cover": "bozicna-zaroka--bozicna-zaroka-1",
    "photos": [
      "bozicna-zaroka--bozicna-zaroka-1",
      "bozicna-zaroka--bozicna-zaroka-10",
      "bozicna-zaroka--bozicna-zaroka-11",
      "bozicna-zaroka--bozicna-zaroka-12",
      "bozicna-zaroka--bozicna-zaroka-13",
      "bozicna-zaroka--bozicna-zaroka-14",
      "bozicna-zaroka--bozicna-zaroka-15",
      "bozicna-zaroka--bozicna-zaroka-16",
      "bozicna-zaroka--bozicna-zaroka-17",
      "bozicna-zaroka--bozicna-zaroka-18",
      "bozicna-zaroka--bozicna-zaroka-2",
      "bozicna-zaroka--bozicna-zaroka-3"
    ]
  },
  {
    "slug": "anja-mitja",
    "title": "Anja & Mitja",
    "kind": "Wedding",
    "cover": "anja-mitja--anjamitja0001",
    "photos": [
      "anja-mitja--anjamitja0001",
      "anja-mitja--anjamitja0015",
      "anja-mitja--anjamitja0020",
      "anja-mitja--anjamitja0021",
      "anja-mitja--anjamitja0023",
      "anja-mitja--anjamitja0026",
      "anja-mitja--anjamitja0028",
      "anja-mitja--anjamitja0031",
      "anja-mitja--anjamitja0036",
      "anja-mitja--anjamitja0047",
      "anja-mitja--anjamitja0064",
      "anja-mitja--anjamitja0065"
    ]
  },
  {
    "slug": "anja-matej",
    "title": "Anja & Matej",
    "kind": "Wedding",
    "cover": "anja-matej--anja-matej-poroka-2020-ana-kete-photo-245",
    "photos": [
      "anja-matej--anja-matej-poroka-2020-ana-kete-photo-245",
      "anja-matej--anja-matej-poroka-2020-ana-kete-photo-246",
      "anja-matej--anja-matej-poroka-2020-ana-kete-photo-249",
      "anja-matej--anja-matej-poroka-2020-ana-kete-photo-26",
      "anja-matej--anja-matej-poroka-2020-ana-kete-photo-260",
      "anja-matej--anja-matej-poroka-2020-ana-kete-photo-261",
      "anja-matej--anja-matej-poroka-2020-ana-kete-photo-262",
      "anja-matej--anja-matej-poroka-2020-ana-kete-photo-263",
      "anja-matej--anja-matej-poroka-2020-ana-kete-photo-265",
      "anja-matej--anja-matej-poroka-2020-ana-kete-photo-266",
      "anja-matej--anja-matej-poroka-2020-ana-kete-photo-267",
      "anja-matej--anja-matej-poroka-2020-ana-kete-photo-268"
    ]
  },
  {
    "slug": "kelly-ervin",
    "title": "Kelly & Ervin",
    "kind": "Wedding",
    "cover": "kelly-ervin--kelly-ervin-day-two-10",
    "photos": [
      "kelly-ervin--kelly-ervin-day-two-10",
      "kelly-ervin--kelly-ervin-day-two-11",
      "kelly-ervin--kelly-ervin-day-two-12",
      "kelly-ervin--kelly-ervin-day-two-120",
      "kelly-ervin--kelly-ervin-day-two-121",
      "kelly-ervin--kelly-ervin-day-two-122",
      "kelly-ervin--kelly-ervin-day-two-123",
      "kelly-ervin--kelly-ervin-day-two-124",
      "kelly-ervin--kelly-ervin-day-two-125",
      "kelly-ervin--kelly-ervin-day-two-126",
      "kelly-ervin--kelly-ervin-day-two-127",
      "kelly-ervin--kelly-ervin-day-two-13"
    ]
  },
  {
    "slug": "kelly-ervin-indijska-poroka",
    "title": "Kelly & Ervin indijska poroka",
    "kind": "Wedding",
    "cover": "kelly-ervin-indijska-poroka--kelly-ervin-day-one-11",
    "photos": [
      "kelly-ervin-indijska-poroka--kelly-ervin-day-one-11",
      "kelly-ervin-indijska-poroka--kelly-ervin-day-one-119",
      "kelly-ervin-indijska-poroka--kelly-ervin-day-one-120",
      "kelly-ervin-indijska-poroka--kelly-ervin-day-one-126",
      "kelly-ervin-indijska-poroka--kelly-ervin-day-one-128",
      "kelly-ervin-indijska-poroka--kelly-ervin-day-one-13",
      "kelly-ervin-indijska-poroka--kelly-ervin-day-one-130",
      "kelly-ervin-indijska-poroka--kelly-ervin-day-one-131",
      "kelly-ervin-indijska-poroka--kelly-ervin-day-one-132",
      "kelly-ervin-indijska-poroka--kelly-ervin-day-one-135",
      "kelly-ervin-indijska-poroka--kelly-ervin-day-one-136",
      "kelly-ervin-indijska-poroka--kelly-ervin-day-one-137"
    ]
  },
  {
    "slug": "eva-in-nejc",
    "title": "Eva & Nejc",
    "kind": "Wedding",
    "cover": "eva-in-nejc--e-n-1234",
    "photos": [
      "eva-in-nejc--e-n-1234",
      "eva-in-nejc--e-n-1252",
      "eva-in-nejc--e-n-1259",
      "eva-in-nejc--e-n-1260",
      "eva-in-nejc--e-n-1268",
      "eva-in-nejc--e-n-1269",
      "eva-in-nejc--e-n-1270",
      "eva-in-nejc--e-n-140",
      "eva-in-nejc--e-n-141",
      "eva-in-nejc--e-n-142",
      "eva-in-nejc--e-n-185",
      "eva-in-nejc--e-n-187"
    ]
  }
];

export const galleryBySlug = (slug: string) => galleries.find((g) => g.slug === slug);
